### ISSUE TITLE
Dependencies fail to install correctly

### ISSUE THREAD

**Issue by SystemFiles** [design1online/WTF-Adventure#8] opened 2019-03-11 20:54 UTC
using `npm install`, It gets to a point where it simply kills the download and does not install dependencies required to run server files.

**Comment by Pelix87** [comment] 2019-03-12 14:16
try `npm install -d`

**Comment by design1online** [comment] 2019-03-12 15:32
@SystemFiles can you tell me where it's failing in the download? Is there a specific package? I know there has been issues in the past with one of the server packages not being available from the npm service (I think it was deleted or deprecated?) and sometimes it works better to install that one separately.

**Comment by Pelix87** [comment] 2019-03-13 08:51
@design1online i think the problem is npm bcrypt ... its bad and doesnt exist anymore :)

**Comment by design1online** [comment] 2019-03-14 02:47
Hmm yeah I know for a while it was having node-gyp issues but that should be fixed with the updated version of node in the package.json. It is currently available in npm (see here: https://www.npmjs.com/package/bcrypt). Try doing `git checkout master && git pull && rm -rf node_modules && npm install` and see if that fixes it for you.

**Closed** 2019-03-15 03:45 UTC
Labels: need more info
